### ISSUE TITLE
Provide integration with Security Monkey

### ISSUE THREAD

**Issue by 0xdabbad00** [sendgrid/krampus#10]
The intro blog post describes how this is used with Security Monkey.  Can you provide more details on how that is done? Ideally in code, but at least a description?

**Comment by signus** [comment]
@0xdabbad00 - We greatly appreciate your submission! I have closed this with an update to the README describing how to set up the tasks file, which is the core of how Krampus is utilized with Security Monkey - namely through the use of a custom alerter (Justice Engine).

Please let us know if you believe we could improve the documentation further.
